spring.application.name=mateus


# Configurações do banco de dados

# Especifica o dialeto do Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações de conexão com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/curso_spring

#Usuario e senha para acessar o banco de dados
spring.datasource.username=postgres
spring.datasource.password=123

#Configurações do Hibernate para criar ou atualizar o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

#Ver os comando acontecendo no console
spring.jpa.generate-ddl=true

#Exibe as consultas SQL geradas pelo Hibernate no console para fins de depuração
spring.jpa.show-sql=true
